GET http://localhost:3000/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0ODU4NzM4LCJleHBpcmVkQXQiOjE2NTQ4NTk2Mzh9.zu37N4Ut8FcP1w-vF7finf4kj6YObwTQVUzSofi70l8

###GET por categoria
GET http://localhost:3000/api/proyectos/categoria/angular
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NjIwODM1LCJleHBpcmVkQXQiOjE2NTQ2MjExMzV9.EVo5etj-YgRaFdgJwrajy1g5bSlL9XoJCGYolPJsBkE

###GET proyecto por ID
GET http://localhost:3000/api/proyectos/62a0662a6f502a490a03e438
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NzA1ODA5LCJleHBpcmVkQXQiOjE2NTQ3MDY3MDl9.KyGTHFyWxZhj7ihR_ohTXdXFX9Zcl_EmfaxeppD-Gsw

###POST de un proyecto
POST http://localhost:3000/api/proyectos
Content-Type: application/json
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NjIwNDg3LCJleHBpcmVkQXQiOjE2NTQ2MjA3ODd9.6SCUYRQI-Zzmt1MfyfSzfOvLI7prxwXA8lNUu1gEuBA

{
    "titulo": "CV Web",
    "descripcion": "Creacion Live Coding",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quiensomos",
    "categoria": "angular"
}

### Modificacion de un proyecto por su ID
PUT http://localhost:3000/api/proyectos/629f27827fd3c718be2fb5c4
Content-Type: application/json
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NjIwODM1LCJleHBpcmVkQXQiOjE2NTQ2MjExMzV9.EVo5etj-YgRaFdgJwrajy1g5bSlL9XoJCGYolPJsBkE

{
    "titulo": "Proyecto EDITADO de nuevo",
    "descripcion": "Esta es la descripcion EDITADA",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quiensomos",
    "categoria": "nodejs"
}

###ELIMINAR UN PROYECTO POR SU ID
DELETE http://localhost:3000/api/proyectos/62a31ad90a4f62da54daa76d
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0ODU3MjQxLCJleHBpcmVkQXQiOjE2NTQ4NTgxNDF9.H_DJg1lLSDR9mtgZveCiGvpYKpGaJu2BGF9yujOC-lU

###
###Para generar un token
GET http://localhost:3000/api/token



#################
###PRODUCCION####
GET https://cvbackoibeas.herokuapp.com/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NjE5NzczLCJleHBpcmVkQXQiOjE2NTQ2MjAwNzN9.91uGrJ9ZYKluXcoAQzDA4kHPWCyg8UZDMGRP0mdHgWk


###
GET https://cvbackoibeas.herokuapp.com/api/token