GET http://localhost:3000/api/proyectos
access-token: eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJ1c3VhcmlvIjoiT2liZWFzIiwiY3JlYXRlZEF0IjoxNjU0NjE4ODg1LCJleHBpcmVkQXQiOjE2NTQ2MTkxODV9.0oypL3dySbt10_1k_RREAYSqyVrp68ALCvd1aR98Whc

###

POST http://localhost:3000/api/proyectos
Content-Type: application/json

{
    "titulo": "Proyecto de prueba2",
    "descripcion": "Esta es la descripcion",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quiensomos"
}

###

PUT http://localhost:3000/api/proyectos/629f27827fd3c718be2fb5c4
Content-Type: application/json

{
    "titulo": "Proyecto EDITADO de nuevo",
    "descripcion": "Esta es la descripcion EDITADA",
    "url": "http://www.google.es",
    "cliente": "Google",
    "url_cliente": "http://www.google.com/quiensomos"
}

###

DELETE http://localhost:3000/api/proyectos/629f23cab6e1e1202654e7b2

###
###Para generar un token
GET http://localhost:3000/api/token
